/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BFormCheckbox: typeof import('bootstrap-vue-next')['BFormCheckbox']
    BFormCheckboxGroup: typeof import('bootstrap-vue-next')['BFormCheckboxGroup']
    BFormGroup: typeof import('bootstrap-vue-next')['BFormGroup']
    BFormRadio: typeof import('bootstrap-vue-next')['BFormRadio']
    ConfDialogWithIcon: typeof import('./src/components/notification/ConfDialogWithIcon.vue')['default']
    ConfirmationDialog: typeof import('./src/components/notification/ConfirmationDialog.vue')['default']
    DataInformasiNasabah: typeof import('./src/components/followupcanvassing/DataInformasiNasabah.vue')['default']
    DataKeputusanComponent: typeof import('./src/components/approvalcanvasing/DataKeputusanComponent.vue')['default']
    DataLeadDetail: typeof import('./src/components/daftarleads/DataLeadDetail.vue')['default']
    DataLeadsNasabah: typeof import('./src/components/kcatakeover/DataLeadsNasabah.vue')['default']
    DataListRiwayatComponent: typeof import('./src/components/daftarleads/DataListRiwayatComponent.vue')['default']
    DataListRiwayatFollowupComponent: typeof import('./src/components/followupcanvassing/DataListRiwayatFollowupComponent.vue')['default']
    DataNasabahApprovalComponent: typeof import('./src/components/approvalcanvasing/DataNasabahApprovalComponent.vue')['default']
    DataNasabahCabangComponent: typeof import('./src/components/followupcanvassing/DataNasabahCabangComponent.vue')['default']
    DataNasabahComponent: typeof import('./src/components/daftarleads/DataNasabahComponent.vue')['default']
    DataNasabahLeadsComponent: typeof import('./src/components/followupcanvassing/DataNasabahLeadsComponent.vue')['default']
    DataNasabahProdukComponent: typeof import('./src/components/followupcanvassing/DataNasabahProdukComponent.vue')['default']
    DataNasabahSosmedComponent: typeof import('./src/components/followupcanvassing/DataNasabahSosmedComponent.vue')['default']
    DataReviewDocumentComponent: typeof import('./src/components/approvalkcatakeover/DataReviewDocumentComponent.vue')['default']
    DataRiwayatTransaksiComponent: typeof import('./src/components/followupcanvassing/DataRiwayatTransaksiComponent.vue')['default']
    DetailApprovalCanvasing: typeof import('./src/components/approvalcanvasing/DetailApprovalCanvasing.vue')['default']
    DetailApprovalKCATakeOver: typeof import('./src/components/approvalkcatakeover/DetailApprovalKCATakeOver.vue')['default']
    DetailFollowup: typeof import('./src/components/daftarleads/DetailFollowup.vue')['default']
    DetailFollowupLeads: typeof import('./src/components/daftarleads/DetailFollowupLeads.vue')['default']
    DetailPengajuanFollowup: typeof import('./src/components/daftarleads/DetailPengajuanFollowup.vue')['default']
    DetailRiwayat: typeof import('./src/components/followupcanvassing/DetailRiwayat.vue')['default']
    ErrorModal: typeof import('./src/components/notification/ErrorModal.vue')['default']
    FollowUpCanvassingComponent: typeof import('./src/components/followupcanvassing/FollowUpCanvassingComponent.vue')['default']
    FollowUpKCATakeOverComponent: typeof import('./src/components/kcatakeover/FollowUpKCATakeOverComponent.vue')['default']
    FooterComponent: typeof import('./src/components/FooterComponent.vue')['default']
    FormPengajuanFollowupCanvasing: typeof import('./src/components/form/FormPengajuanFollowupCanvasing.vue')['default']
    FormPengajuanFollowupKCATakeOver: typeof import('./src/components/form/FormPengajuanFollowupKCATakeOver.vue')['default']
    FormTahapanFollowupCanvasing: typeof import('./src/components/form/FormTahapanFollowupCanvasing.vue')['default']
    FormTahapanFollowupKCATakeOver: typeof import('./src/components/form/FormTahapanFollowupKCATakeOver.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    LoadingDialog: typeof import('./src/components/notification/LoadingDialog.vue')['default']
    NumberingComponent: typeof import('./src/components/NumberingComponent.vue')['default']
    QuestionCheckComponent: typeof import('./src/components/QuestionCheckComponent.vue')['default']
    RadioComponent: typeof import('./src/components/RadioComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StepperComponent: typeof import('./src/components/form/StepperComponent.vue')['default']
    StickyFooterBtn: typeof import('./src/components/StickyFooterBtn.vue')['default']
    TableComponent: typeof import('./src/components/TableComponent.vue')['default']
  }
}
